apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels: 
        app: backend
    spec:
      containers:
      - name: backend
        image: anuplohar001/backend:latest
        ports:
          - containerPort: 3000
        env:
          
        imagePullPolicy: IfNotPresent